import React, {useEffect, useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const reasons=['Devolución y Ajuste de precios','Devolución','Descuento','Bonificación','Crédito incobrable','Recupero de costo','Recupero de gasto','Ajuste de precio'];
const initial={establishment:'001',point:'004',number:'',date:'',reason:'1',single:false,code:'',quantity:'',amount:''};
function App(){
  const [options,setOptions]=useState(initial),[xml,setXml]=useState(''),[json,setJson]=useState(''),[summary,setSummary]=useState(''),[status,setStatus]=useState('Pegá un XML o seleccioná un archivo.'),[busy,setBusy]=useState(false);
  const [files,setFiles]=useState([]),[selected,setSelected]=useState(''),[filter,setFilter]=useState(''),[view,setView]=useState('todos'),[done,setDone]=useState(()=>{try{return JSON.parse(localStorage.getItem('nc-realizados')||'{}')}catch{return {}}});
  const [query,setQuery]=useState(''),[match,setMatch]=useState(0),[tab,setTab]=useState('convertir');
  const [authUrl,setAuthUrl]=useState(''),[sendUrl,setSendUrl]=useState(''),[credentials,setCredentials]=useState('{\n  "ruc": "",\n  "password": ""\n}'),[token,setToken]=useState(''),[payload,setPayload]=useState(''),[response,setResponse]=useState('');
  const editor=useRef(null),folder=useRef(null),singleFile=useRef(null),requestId=useRef(0);
  useEffect(()=>localStorage.setItem('nc-realizados',JSON.stringify(done)),[done]);
  // Igual que la versión Java: regenerar tras modificar XML o datos de la NC.
  useEffect(()=>{if(!xml.trim())return;const timer=setTimeout(()=>convert(),600);return()=>clearTimeout(timer)},[xml,options]);
  const update=(key,value)=>{requestId.current++;setOptions(prev=>({...prev,[key]:value}));setJson('');setSummary('')};
  const load=(file)=>{if(!file)return;requestId.current++;const reader=new FileReader();reader.onload=()=>{setXml(String(reader.result).replace(/^\uFEFF/,''));setJson('');setSummary('');setSelected(file.webkitRelativePath||file.name);setStatus(`Archivo cargado: ${file.name}`)};reader.onerror=()=>setStatus('No se pudo leer el archivo.');reader.readAsText(file,'UTF-8')};
  const importFiles=(list)=>{const incoming=[...list].filter(f=>/\.(xml|txt)$/i.test(f.name)).sort((a,b)=>a.name.localeCompare(b.name));setFiles(incoming);if(incoming.length)load(incoming[0]);else setStatus('No hay archivos XML o TXT en la selección.')};
  const visible=useMemo(()=>files.filter(f=>f.name.toLowerCase().includes(filter.toLowerCase())&&(view==='todos'||(view==='realizados'?!!done[f.webkitRelativePath||f.name]:!done[f.webkitRelativePath||f.name]))),[files,filter,view,done]);
  const matches=useMemo(()=>{if(!query||!json)return [];const found=[];let at=0;while((at=json.toLowerCase().indexOf(query.toLowerCase(),at))!==-1){found.push(at);at+=Math.max(query.length,1)}return found},[json,query]);
  const jump=(index)=>{if(!matches.length)return;const next=(index+matches.length)%matches.length;setMatch(next);editor.current?.focus();editor.current?.setSelectionRange(matches[next],matches[next]+query.length)};
  async function convert(){const id=++requestId.current;setBusy(true);setStatus('Generando NC…');try{const res=await fetch('/api/convert',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...options,xml})});const raw=await res.text();if(!raw.trim())throw Error('El servidor Java no devolvió datos. Revisá que esté ejecutándose en el puerto 8765.');let body;try{body=JSON.parse(raw)}catch{throw Error('El servidor devolvió una respuesta inválida. Revisá la terminal Java.')}if(!res.ok)throw Error(body.error||'No se pudo convertir.');if(id!==requestId.current)return;setJson(body.json);setPayload(body.json);setSummary(`${body.count} producto(s) · ${body.summary}`);setStatus(options.number&&options.date?'NC creada. Revisá los datos antes de enviar.':'Borrador creado: completá número y fecha de NC antes de enviar.');setMatch(0)}catch(error){if(id!==requestId.current)return;setJson('');setStatus(error.message)}finally{if(id===requestId.current)setBusy(false)}}
  const download=(extension)=>{const blob=new Blob([json],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`NC_${options.number||'resultado'}.${extension}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
  const copy=async value=>{try{await navigator.clipboard.writeText(value);setStatus('Copiado al portapapeles.')}catch{setStatus('No se pudo copiar: usá Ctrl+C.')}};
  function extractToken(value){let t=value.trim();if(t.startsWith('{')||t.startsWith('[')){const found=[];const scan=x=>{if(Array.isArray(x))x.forEach(scan);else if(x&&typeof x==='object')Object.entries(x).forEach(([k,v])=>{if(['token','access_token','accesstoken','bearer'].includes(k.toLowerCase())&&typeof v==='string'&&v.trim())found.push(v);else scan(v)})};scan(JSON.parse(t));const unique=[...new Set(found)];if(unique.length!==1)throw Error('La respuesta no contiene un token único.');t=unique[0]}t=t.replace(/^Bearer\s+/i,'').trim();if(!/^[A-Za-z0-9._~+/=-]+$/.test(t))throw Error('Token inválido.');return t}
  async function send(auth){try{const url=new URL(auth?authUrl:sendUrl);if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw Error('Ingresá una URL HTTP o HTTPS válida.');const body=auth?credentials:payload;const parsed=JSON.parse(body);if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw Error('El JSON debe ser un objeto.');if(auth&&(!parsed.ruc||!parsed.password))throw Error('Completá ruc y password.');const bearer=auth?'':extractToken(token);setBusy(true);setResponse('Enviando…');if(auth)setToken('');const res=await fetch('/api/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:url.href,body,token:bearer})});const result=await res.json();if(!res.ok)throw Error(result.error||'No se completó el envío.');const text=result.body;setResponse(`HTTP ${result.status}\n\n${text}`);if(auth&&result.status>=200&&result.status<300)setToken(extractToken(text));setStatus(result.status>=200&&result.status<300?(auth?'Token listo.':'Respuesta recibida. Revisá el estado fiscal de la NC.'):`HTTP ${result.status}: revisá la respuesta.`)}catch(error){setResponse(String(error));setStatus(error instanceof TypeError?'No se pudo conectar con la función web.':error.message)}finally{setBusy(false)}}
  return <div className="app"><header><div><span className="eyebrow">CONVERSOR LOCAL</span><h1>Factura XML → Nota de crédito</h1><p>Generá una NC desde un XML de factura electrónica y revisá el JSON antes de enviarlo.</p></div><div className="tabs"><button className={tab==='convertir'?'active':''} onClick={()=>setTab('convertir')}>Convertir</button><button className={tab==='envio'?'active':''} onClick={()=>setTab('envio')}>Acceso y envío</button></div></header>
  {tab==='convertir'?<main><aside className="card folder"><div className="title"><h2>Archivos XML/TXT</h2><span>{files.length} encontrados</span></div><button className="secondary full" onClick={()=>folder.current?.click()}>Abrir carpeta</button><input ref={folder} hidden type="file" webkitdirectory="" directory="" multiple onChange={e=>importFiles(e.target.files)}/><button className="secondary full" onClick={()=>singleFile.current?.click()}>Seleccionar XML o TXT</button><input ref={singleFile} hidden type="file" accept=".xml,.txt,text/xml,text/plain" onChange={e=>importFiles(e.target.files)}/><input placeholder="Buscar por nombre…" value={filter} onChange={e=>setFilter(e.target.value)}/><div className="segmented">{['todos','pendientes','realizados'].map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{v}</button>)}</div><div className="filelist">{visible.map((f,i)=><div className={'file '+(selected===f.name?'selected':'')} key={f.webkitRelativePath||f.name+i}><button title={f.webkitRelativePath||f.name} onClick={()=>load(f)}>{f.name}</button><label title="Marcar realizado"><input type="checkbox" checked={!!done[f.webkitRelativePath||f.name]} onChange={e=>setDone(prev=>({...prev,[f.webkitRelativePath||f.name]:e.target.checked}))}/> ✓</label></div>)}{!visible.length&&<small>No hay archivos en esta vista.</small>}</div><small>Al abrir una carpeta solo se listan XML y TXT. Seleccioná uno para generar la NC.</small></aside>
  <section className="work"><div className="card"><div className="title"><h2>01 · Factura de origen</h2><button className="secondary" onClick={()=>{setXml('');setJson('');setSummary('');setSelected('');setStatus('Entrada limpia.')}}>Limpiar</button></div><textarea className="xml" spellCheck="false" placeholder="Pegá aquí el XML completo de la factura…" value={xml} onChange={e=>{setXml(e.target.value);setJson('');setSummary('')}}/><small>{selected||'También podés pegar el texto copiado del navegador.'}</small></div>
  <div className="card"><h2>02 · Datos de la nueva NC</h2><div className="grid">{[['establishment','Establecimiento','001'],['point','Punto de expedición','004'],['number','Número de NC (7 dígitos)','0000001'],['date','Fecha y hora','AAAA-MM-DDThh:mm:ss']].map(([key,label,placeholder])=><label key={key}>{label}<input placeholder={placeholder} value={options[key]} onChange={e=>update(key,e.target.value)}/></label>)}<label className="wide">Motivo<select value={options.reason} onChange={e=>update('reason',e.target.value)}>{reasons.map((r,i)=><option key={r} value={i+1}>{i+1} · {r}</option>)}</select></label></div><label className="check"><input type="checkbox" checked={options.single} onChange={e=>update('single',e.target.checked)}/> NC parcial</label>{options.single&&<div className="grid"><label>Códigos separados por ;<input value={options.code} placeholder="682;510" onChange={e=>update('code',e.target.value)}/></label><label>Cantidades separadas por ;<input value={options.quantity} placeholder="1;2" onChange={e=>update('quantity',e.target.value)}/></label><label className="wide">Monto total a acreditar (sin separador de miles)<input value={options.amount} placeholder="13801513" onChange={e=>update('amount',e.target.value)}/></label></div>}<button className="primary full" disabled={busy||!xml.trim()} onClick={convert}>{busy?'Procesando…':'Crear NC'}</button></div>
  <div className="card"><div className="title"><h2>03 · JSON generado</h2><div className="actions"><button disabled={!json} onClick={()=>copy(json)}>Copiar</button><button disabled={!json} onClick={()=>download('json')}>Guardar JSON</button><button disabled={!json} onClick={()=>download('txt')}>Guardar TXT</button></div></div><div className="search"><input placeholder="Buscar campo o valor en JSON…" value={query} onChange={e=>{setQuery(e.target.value);setMatch(0)}}/><button disabled={!matches.length} onClick={()=>jump(match-1)}>↑</button><button disabled={!matches.length} onClick={()=>jump(match+1)}>↓</button><span>{matches.length?`${match+1}/${matches.length}`:'0 resultados'}</span></div><textarea ref={editor} className="output" spellCheck="false" value={json} onChange={e=>setJson(e.target.value)} placeholder="El resultado aparecerá aquí…"/><small>{summary||'El campo encontrado se selecciona para facilitar la revisión.'}</small></div></section></main>:<div className="sendgrid"><div className="card"><h2>01 · Acceso</h2><label>URL de autenticación<input value={authUrl} onChange={e=>setAuthUrl(e.target.value)} placeholder="https://…/api/autenticate"/></label><label>Credenciales JSON<textarea value={credentials} onChange={e=>setCredentials(e.target.value)}/></label><button className="primary" disabled={busy} onClick={()=>send(true)}>Generar token</button><label>Token<textarea value={token} onChange={e=>setToken(e.target.value)}/></label><div className="actions"><button onClick={()=>{try{setToken(extractToken(token));setStatus('Token listo.')}catch(e){setStatus(e.message)}}}>Leer token</button><button onClick={()=>copy(token)}>Copiar token</button></div></div><div className="card"><h2>02 · Enviar NC</h2><label>URL de envío<input value={sendUrl} onChange={e=>setSendUrl(e.target.value)} placeholder="https://…/api/operation"/></label><button onClick={()=>setPayload(json)} disabled={!json}>Usar NC creada</button><label>Documento JSON editable<textarea className="payload" value={payload} onChange={e=>setPayload(e.target.value)}/></label><button className="primary" disabled={busy||!payload} onClick={()=>send(false)}>Enviar NC</button></div><div className="card"><h2>03 · Respuesta</h2><textarea className="payload" readOnly value={response}/><button onClick={()=>copy(response)}>Copiar respuesta</button><small>HTTP 200 no confirma aprobación fiscal. Revisá la respuesta del servicio.</small></div></div>}
  <div className="status" role="status">{status}</div></div>
}
createRoot(document.getElementById('root')).render(<App/>);
